#!/bin/bash
# Set up custom Showdown formats for training without gimmicks.
#
# Creates pokemon-showdown/config/custom-formats.ts with:
#   - [Gen 8] Random Battle (No Gimmicks)  — no Dynamax, no Sleep Clause
#   - [Gen 9] Random Battle (No Gimmicks)  — no Terastallize, no Sleep Clause
#   - [Gen 8] Custom Game (No Gimmicks)    — no Dynamax (for fixed team)
#   - [Gen 9] Custom Game (No Gimmicks)    — no Terastallize (for fixed team)
#
# Restart your Showdown servers after running this.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SHOWDOWN_DIR="$PROJECT_DIR/pokemon-showdown"

if [ ! -d "$SHOWDOWN_DIR" ]; then
    echo "Error: $SHOWDOWN_DIR not found."
    exit 1
fi

CONFIG_DIR="$SHOWDOWN_DIR/config"
mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_DIR/custom-formats.ts" << 'FORMATS_EOF'
// Custom formats for RL training — no gimmicks, no sleep clause.
// Generated by scripts/setup_custom_formats.sh

export const Formats: import('../sim/dex-formats').FormatList = [

	{
		section: "Custom",
	},

	// --- Random Battle variants (random teams) ---

	{
		name: "[Gen 8] Random Battle (No Gimmicks)",
		desc: `Randomized teams. No Dynamax, no Sleep Clause.`,
		mod: 'gen8',
		team: 'random',
		bestOfDefault: true,
		searchShow: true,
		challengeShow: true,
		ruleset: [
			'[Gen 8] Random Battle',
			'Dynamax Clause',
			'!Sleep Clause Mod',
		],
	},
	{
		name: "[Gen 9] Random Battle (No Gimmicks)",
		desc: `Randomized teams. No Terastallize, no Sleep Clause.`,
		mod: 'gen9',
		team: 'random',
		bestOfDefault: true,
		searchShow: true,
		challengeShow: true,
		ruleset: [
			'[Gen 9] Random Battle',
			'Terastal Clause',
			'!Sleep Clause Mod',
		],
	},

	// --- Custom Game variants (fixed team) ---
	// Note: no '!Sleep Clause Mod' here because the base Custom Game
	// format doesn't include Sleep Clause Mod — trying to remove it crashes.

	{
		name: "[Gen 8] Custom Game (No Gimmicks)",
		mod: 'gen8',
		searchShow: true,
		challengeShow: true,
		battle: { trunc: Math.trunc },
		ruleset: [
			'Team Preview', 'Cancel Mod',
			'Max Team Size = 24', 'Max Move Count = 24',
			'Max Level = 9999', 'Default Level = 100',
			'Dynamax Clause',
		],
	},
	{
		name: "[Gen 9] Custom Game (No Gimmicks)",
		mod: 'gen9',
		searchShow: true,
		challengeShow: true,
		battle: { trunc: Math.trunc },
		ruleset: [
			'Team Preview', 'Cancel Mod',
			'Max Team Size = 24', 'Max Move Count = 24',
			'Max Level = 9999', 'Default Level = 100',
			'Terastal Clause',
		],
	},

];
FORMATS_EOF

echo "Created $CONFIG_DIR/custom-formats.ts"
echo "Restart your Showdown servers to pick up the new formats:"
echo "  ./scripts/kill_all_showdown.sh && ./scripts/spin_up_multiple_showdown.sh"
